#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   Issue #350 is still open: on Windows, the code here causes it to link
   with PYTHON36.DLL (for example) instead of PYTHON3.DLL.  A fix was
   attempted in 164e526a5515 and 14ce6985e1c3, but reverted: virtualenv
   does not make PYTHON3.DLL available, and so the "correctly" compiled
   version would not run inside a virtualenv.  We will re-apply the fix
   after virtualenv has been fixed for some time.  For explanation, see
   issue #355.  For a workaround if you want PYTHON3.DLL and don't worry
   about virtualenv, see issue #350.  See also 'py_limited_api' in
   setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t(x);
}


/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


                      #include <stdio.h>
                      #include <stdint.h>
                      #include <blosc.h>
                      #include <time.h>
                      
                      int calculate_j(int k, int dim[], int s[], int sb[]) {
                      

                            int j = dim[0]*((k)%sb[0] + k/(sb[0]*sb[1]*sb[2]*sb[3]*sb[4]*sb[5]*sb[6]*sb[7])%(s[0]/sb[0])*sb[0])
                                +
                                dim[1]*(k/(sb[0])%sb[1]*s[0] + k/(s[0]*sb[1]*sb[2]*sb[3]*sb[4]*sb[5]*sb[6]*sb[7])%(s[1]/sb[1])*s[0]*sb[1])
                                +
                                dim[2]*(k/(sb[0]*sb[1])%sb[2]*s[1]*s[0] + k/(s[0]*s[1]*sb[2]*sb[3]*sb[4]*sb[5]*sb[6]*sb[7])%(s[2]/sb[2])*s[0]*s[1]*sb[2])
                                +
                                dim[3]*(k/(sb[0]*sb[1]*sb[2])%sb[3]*s[0]*s[1]*s[2] + k/(s[0]*s[1]*s[2]*sb[3]*sb[4]*sb[5]*sb[6]*sb[7])%(s[3]/sb[3])*s[0]*s[1]*s[2]*sb[3])
                                +
                                dim[4]*(k/(sb[0]*sb[1]*sb[2]*sb[3])%sb[4]*s[0]*s[1]*s[2]*s[3] + k/(s[0]*s[1]*s[2]*s[3]*sb[4]*sb[5]*sb[6]*sb[7])%(s[4]/sb[4])*s[0]*s[1]*s[2]*s[3]*sb[4])
                                +
                                dim[5]*(k/(sb[0]*sb[1]*sb[2]*sb[3]*sb[4])%sb[5]*s[0]*s[1]*s[2]*s[3]*s[4] + k/(s[0]*s[1]*s[2]*s[3]*s[4]*sb[5]*sb[6]*sb[7])%(s[5]/sb[5])*s[0]*s[1]*s[2]*s[3]*s[4]*sb[5])
                                +
                                dim[6]*(k/(sb[0]*sb[1]*sb[2]*sb[3]*sb[4]*sb[5])%sb[6]*s[0]*s[1]*s[2]*s[3]*s[4]*s[5] + k/(s[0]*s[1]*s[2]*s[3]*s[4]*s[5]*sb[6]*sb[7])%(s[6]/sb[6])*s[0]*s[1]*s[2]*s[3]*s[4]*s[5]*sb[6])
                                +
                                dim[7]*(k/(sb[0]*sb[1]*sb[2]*sb[3]*sb[4]*sb[5]*sb[6])%sb[7]*s[0]*s[1]*s[2]*s[3]*s[4]*s[5]*s[6] + k/(s[0]*s[1]*s[2]*s[3]*s[4]*s[5]*s[6]*sb[7])%(s[7]/sb[7])*s[0]*s[1]*s[2]*s[3]*s[4]*s[5]*s[6]*sb[7]);
                        
                                return j;
                      }
                      
                      void padData(char* src, char* dest, int typesize, int shape[], int pad_shape[], int dimension) {
                      
                          int MAX_DIM = 8;
                          int DIM = dimension;
                      
                          int s[MAX_DIM], ps[MAX_DIM];
                      
                          for (int i = 0; i < MAX_DIM; i++) {
                              if (i < DIM) {
                                  s[MAX_DIM + i - DIM] = shape[i];
                                  ps[MAX_DIM + i - DIM] = pad_shape[i];
                              } else {
                                  s[MAX_DIM - i - 1] = 1;
                                  ps[MAX_DIM - i - 1] = 1;
                              }
                          }
                      
                          int k, k2;
                      
                          for (int a = 0; a < s[0]; a++) {
                              for (int b = 0; b < s[1]; b++) {
                                  for (int c = 0; c < s[2]; c++) {
                                      for (int d = 0; d < s[3]; d++) {
                                          for (int e = 0; e < s[4]; e++) {
                                              for (int f = 0; f < s[5]; f++) {
                                                  for (int g = 0; g < s[6]; g++) {
                      
                                                      k =  g*s[7]
                                                           + f*s[7]*s[6]
                                                           + e*s[7]*s[6]*s[5]
                                                           + d*s[7]*s[6]*s[5]*s[4]
                                                           + c*s[7]*s[6]*s[5]*s[4]*s[3]
                                                           + b*s[7]*s[6]*s[5]*s[4]*s[3]*s[2]
                                                           + a*s[7]*s[6]*s[5]*s[4]*s[3]*s[2]*s[1];
                      
                                                      k2 = g*ps[7]
                                                           + f*ps[7]*ps[6]
                                                           + e*ps[7]*ps[6]*ps[5]
                                                           + d*ps[7]*ps[6]*ps[5]*ps[4]
                                                           + c*ps[7]*ps[6]*ps[5]*ps[4]*ps[3]
                                                           + b*ps[7]*ps[6]*ps[5]*ps[4]*ps[3]*ps[2]
                                                           + a*ps[7]*ps[6]*ps[5]*ps[4]*ps[3]*ps[2]*ps[1];
                      
                                                      memcpy(&dest[k2 * typesize], &src[k *  typesize], s[7] * typesize);
                                                  }
                                              }
                                          }
                                      }
                                  }
                              }
                          }
                      }
                      
                      void tData_simple(char* src, char* dest, int typesize, int sub_shape[], int shape[], int dimension,
                                        int inverse) {
                      
                          int MAX_DIM = 8;
                          int DIM = dimension;
                      
                          int s[MAX_DIM], sb[MAX_DIM];
                                     
                          for (int i = 0; i < MAX_DIM; i++) {
                              if (i < DIM) {
                                  s[MAX_DIM + i - DIM] = shape[i];
                                  sb[MAX_DIM + i - DIM] = sub_shape[i];
                              } else {
                                  s[MAX_DIM - i - 1] = 1;
                                  sb[MAX_DIM - i - 1] = 1;
                              }
                          }
                      
                          int dim[MAX_DIM], shp[MAX_DIM], sub[MAX_DIM];

                          for (int i = 0; i < MAX_DIM; i++) {
                                if (i < DIM) {
                                    dim[i] = 1;
                                    shp[DIM - i - 1] = shape[i];
                                    sub[DIM - i - 1] = sub_shape[i];
                                } else {
                                    dim[i] = 0;
                                    shp[i] = 1;
                                    sub[i] = 1;
                                }
                            }
                                       
                          int k, j;
                          
                          for (int i = 0; i < 8; i++) {
                            printf("%d -- ", sub[i]);
                          }
                          
                          if (inverse == 0) {
                              for (int a = 0; a < s[0]; a++) {
                                  for (int b = 0; b < s[1]; b++) {
                                      for (int c = 0; c < s[2]; c++) {
                                          for (int d = 0; d < s[3]; d++) {
                                              for (int e = 0; e < s[4]; e++) {
                                                  for (int f = 0; f < s[5]; f++) {
                                                      for (int g = 0; g < s[6]; g++) {
                                                          for (int h = 0; h < s[7]; h+=sb[7]) {
                      
                                                              k =  h
                                                                   + g*s[7]
                                                                   + f*s[7]*s[6]
                                                                   + e*s[7]*s[6]*s[5]
                                                                   + d*s[7]*s[6]*s[5]*s[4]
                                                                   + c*s[7]*s[6]*s[5]*s[4]*s[3]
                                                                   + b*s[7]*s[6]*s[5]*s[4]*s[3]*s[2]
                                                                   + a*s[7]*s[6]*s[5]*s[4]*s[3]*s[2]*s[1];
                                                                   
                                                              printf("%d - ", h);
                                                              
                                                              j = calculate_j(k, dim, shp, sub);
                      
                                                              memcpy(&dest[k * typesize], &src[j * typesize], typesize * sb[7]);
                      
                      
                                                          }
                                                      }
                                                  }
                                              }
                                          }
                                      }
                                  }
                              }
                      
                          } else {
                              for (int a = 0; a < s[0]; a++) {
                                  for (int b = 0; b < s[1]; b++) {
                                      for (int c = 0; c < s[2]; c++) {
                                          for (int d = 0; d < s[3]; d++) {
                                              for (int e = 0; e < s[4]; e++) {
                                                  for (int f = 0; f < s[5]; f++) {
                                                      for (int g = 0; g < s[6]; g++) {
                                                          for (int h = 0; h < s[7]; h+=sb[7]) {
                      
                                                              k =  h
                                                                   + g*s[7]
                                                                   + f*s[7]*s[6]
                                                                   + e*s[7]*s[6]*s[5]
                                                                   + d*s[7]*s[6]*s[5]*s[4]
                                                                   + c*s[7]*s[6]*s[5]*s[4]*s[3]
                                                                   + b*s[7]*s[6]*s[5]*s[4]*s[3]*s[2]
                                                                   + a*s[7]*s[6]*s[5]*s[4]*s[3]*s[2]*s[1];
                                                                   
                                                              printf("%d - ", h);
                                                              
                                                              j = calculate_j(k, dim, s, sb);
                      
                                                              memcpy(&dest[j * typesize], &src[k * typesize], typesize * sb[7]);
                      
                      
                                                          }
                                                      }
                                                  }
                                              }
                                          }
                                      }
                                  }
                              }
                          }
                      }
                      
                      void tData(char* src, char* dest, int typesize, int shape[], int pad_shape[],
                                int sub_shape[], int size, int dimension, int inverse) {
                      
                      
                          char* src_aux = (char *) calloc (size, typesize);
                      
                          padData(src, src_aux, typesize, shape, pad_shape, dimension);
                      
                          tData_simple(src_aux, dest, typesize, sub_shape, pad_shape, dimension, inverse);
                      
                      }
                      
                      void decompress_trans(char* comp, char* dest2, int shape[], int trans_shape[], int part_shape[],
                                            int final_s[], int dimensions[], int dimension, int b_size, int typesize){
                      
                          int MAX_DIM = 8;
                          int DIM = dimension;
                      
                          // Calculate dimensions data
                      
                          int subpl[MAX_DIM], ts[MAX_DIM], ps[MAX_DIM], dim[MAX_DIM], sd[MAX_DIM], fs[MAX_DIM], s[MAX_DIM];
                      
                          for (int i = 0; i < MAX_DIM; i++) {
                              if (i < DIM) {
                                  s[MAX_DIM + i - DIM] = shape[i];
                                  ts[MAX_DIM + i - DIM] = trans_shape[i];
                                  ps[MAX_DIM + i - DIM] = part_shape[i];
                                  dim[MAX_DIM + i - DIM] = dimensions[i];
                                  fs[MAX_DIM + i - DIM] = final_s[i];
                                  sd[MAX_DIM + i - DIM] = trans_shape[i]/part_shape[i];
                      
                              } else {
                                  s[MAX_DIM - i - 1] = 1;
                                  ts[MAX_DIM - i - 1] = 1;
                                  ps[MAX_DIM - i - 1] = 1;
                                  dim[MAX_DIM - i - 1] = -1;
                                  sd[MAX_DIM - i - 1] = 1;
                                  fs[MAX_DIM - i - 1] = 1;
                      
                              }
                      
                          }
                      
                          int oi_s[MAX_DIM], oi_f[MAX_DIM];
                      
                      
                          for (int i = 0; i < MAX_DIM; i++) {
                              if (dim[i] != -1) {
                                  subpl[i] = ps[i];
                                  oi_s[i] = dim[i];
                                  oi_f[i] = dim[i] + 1;
                              } else {
                                  subpl[i] = ts[i];
                                  oi_s[i] = 0;
                                  oi_f[i] = ts[i];
                              }
                          }
                      
                          int subpl_size = 1;
                      
                          for (int i = 0; i < MAX_DIM; i++) {
                              subpl_size *= subpl[i];
                          }
                      
                          // Malloc buffers
                      
                          char *aux = malloc(b_size * typesize);
                          char *dest = malloc(subpl_size * typesize);
                      
                          // Calculate index to decompress
                      
                          int k, n;
                          int h2, g2, f2, e2, d2, c2, b2, a2;
                          int cont;
                      
                          for (int a = oi_s[0]/ps[0]*ps[0]; a < oi_f[0]; a += ps[0]) {
                              for (int b = oi_s[1]/ps[1]*ps[1]; b < oi_f[1]; b += ps[1]) {
                                  for (int c = oi_s[2]/ps[2]*ps[2]; c < oi_f[2]; c += ps[2]) {
                                      for (int d = oi_s[3]/ps[3]*ps[3]; d < oi_f[3]; d += ps[3]) {
                                          for (int e = oi_s[4]/ps[4]*ps[4]; e < oi_f[4]; e += ps[4]) {
                                              for (int f = oi_s[5]/ps[5]*ps[5]; f < oi_f[5]; f += ps[5]) {
                                                  for (int g = oi_s[6]/ps[6]*ps[6]; g < oi_f[6]; g += ps[6]) {
                                                      for (int h = oi_s[7]/ps[7]*ps[7]; h < oi_f[7]; h += ps[7]) {
                      
                                                          k = h
                                                               + g*ts[7]
                                                               + f*ts[7]*ts[6]
                                                               + e*ts[7]*ts[6]*ts[5]
                                                               + d*ts[7]*ts[6]*ts[5]*ts[4]
                                                               + c*ts[7]*ts[6]*ts[5]*ts[4]*ts[3]
                                                               + b*ts[7]*ts[6]*ts[5]*ts[4]*ts[3]*ts[2]
                                                               + a*ts[7]*ts[6]*ts[5]*ts[4]*ts[3]*ts[2]*ts[1];
                      
                                                           n = a/ps[0]*sd[1]*sd[2]*sd[3]*sd[4]*sd[5]*sd[6]*sd[7]
                                                              + b/ps[1]*sd[2]*sd[3]*sd[4]*sd[5]*sd[6]*sd[7]
                                                              + c/ps[2]*sd[3]*sd[4]*sd[5]*sd[6]*sd[7]
                                                              + d/ps[3]*sd[4]*sd[5]*sd[6]*sd[7]
                                                              + e/ps[4]*sd[5]*sd[6]*sd[7]
                                                              + f/ps[5]*sd[6]*sd[7]
                                                              + g/ps[6]*sd[7]
                                                              + h/ps[7];
                      
                      
                                                          blosc_getitem(comp, n * b_size, b_size, aux);
                      
                                                          h2 = k % ts[7] % subpl[7];
                                                          g2 = k / (ts[7]) % subpl[6];
                                                          f2 = k / (ts[7]*ts[6]) % subpl[5];
                                                          e2 = k / (ts[7]*ts[6]*ts[5]) % subpl[4];
                                                          d2 = k / (ts[7]*ts[6]*ts[5]*ts[4]) % subpl[3];
                                                          c2 = k / (ts[7]*ts[6]*ts[5]*ts[4]*ts[3]) % subpl[2];
                                                          b2 = k / (ts[7]*ts[6]*ts[5]*ts[4]*ts[3]*ts[2]) % subpl[1];
                                                          a2 = k / (ts[7]*ts[6]*ts[5]*ts[4]*ts[3]*ts[2]*ts[1]) % subpl[0];
                      
                                                          // Copy block to final data
                      
                                                          cont = 0;
                      
                                                          for (int ra = a2; ra < a2 + ps[0]; ra++) {
                                                              for (int rb = b2; rb < b2 + ps[1]; rb++) {
                                                                  for (int rc = c2; rc < c2 + ps[2]; rc++) {
                                                                      for (int rd = d2; rd < d2 + ps[3]; rd++) {
                                                                          for (int re = e2; re < e2 + ps[4]; re++) {
                                                                              for (int rf = f2; rf < f2 + ps[5]; rf++) {
                                                                                  for (int rg = g2; rg < g2 + ps[6]; rg++) {
                      
                                                                                      k = h2
                                                                                           + rg * subpl[7]
                                                                                           + rf * subpl[7]*subpl[6]
                                                                                           + re * subpl[7]*subpl[6]*subpl[5]
                                                                                           + rd * subpl[7]*subpl[6]*subpl[5]*subpl[4]
                                                                                           + rc * subpl[7]*subpl[6]*subpl[5]*subpl[4]*subpl[3]
                                                                                           + rb * subpl[7]*subpl[6]*subpl[5]*subpl[4]*subpl[3]*subpl[2]
                                                                                           + ra * subpl[7]*subpl[6]*subpl[5]*subpl[4]*subpl[3]*subpl[2]*subpl[1];
                      
                                                                                      memcpy(&dest[k * typesize], &aux[cont * typesize], ps[7] * typesize);
                                                                                      cont += ps[7];
                                                                                  }
                                                                              }
                                                                          }
                                                                      }
                                                                  }
                                                              }
                                                          }
                      
                                                      }
                                                  }
                                              }
                                          }
                                      }
                                  }
                             }
                      
                      
                          }
                      
                          // Reduce final data
                      
                          int ini[MAX_DIM], fin[MAX_DIM];
                      
                          for (int i = 0; i < MAX_DIM - 1; i += 1) {
                              if (dim[i] != -1) {
                                  ini[i] = dim[i] % ps[i];
                                  fin[i] = dim[i] % ps[i] + 1;
                              }
                              else {
                                  ini[i] = 0;
                                  fin[i] = s[i];
                              }
                          }
                      
                          if (dim[MAX_DIM - 1] != -1) {
                              ini[MAX_DIM - 1] = dim[MAX_DIM - 1] % ps[MAX_DIM - 1];
                              fin[MAX_DIM - 1] = dim[MAX_DIM - 1] % ps[MAX_DIM - 1] + 1 ;
                          } else {
                              ini[MAX_DIM - 1] = 0;
                              fin[MAX_DIM - 1] = 1;
                          }
                      
                          cont = 0;
                      
                          for (int a = ini[0]; a < fin[0]; a += 1) {
                              for (int b = ini[1]; b < fin[1]; b += 1) {
                                  for (int c = ini[2]; c < fin[2]; c += 1) {
                                      for (int d = ini[3]; d < fin[3]; d += 1) {
                                          for (int e = ini[4]; e < fin[4]; e += 1) {
                                              for (int f = ini[5]; f < fin[5]; f += 1) {
                                                  for (int g = ini[6]; g < fin[6]; g += 1) {
                                                      for (int h = ini[7]; h < fin[7]; h += 1) {
                                                          k = h
                                                               + g * subpl[7]
                                                               + f * subpl[7]*subpl[6]
                                                               + e * subpl[7]*subpl[6]*subpl[5]
                                                               + d * subpl[7]*subpl[6]*subpl[5]*subpl[4]
                                                               + c * subpl[7]*subpl[6]*subpl[5]*subpl[4]*subpl[3]
                                                               + b * subpl[7]*subpl[6]*subpl[5]*subpl[4]*subpl[3]*subpl[2]
                                                               + a * subpl[7]*subpl[6]*subpl[5]*subpl[4]*subpl[3]*subpl[2]*subpl[1];
                      
                                                          memcpy(&dest2[cont * typesize], &dest[k * typesize], fs[7] * typesize);
                      
                                                          cont += fs[7];
                                                      }
                                                  }
                                              }
                                          }
                                      }
                                  }
                              }
                          }
                          free(aux);
                          free(dest);
                      }
                      
                      

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // int()(int, int *, int *, int *)
/*  1 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 1), // int *
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION, 47), // void()(char *, char *, int *, int *, int *, int *, int *, int, int, int)
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 46), // char *
/*  8 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/*  9 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 10 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 13 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 14 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 15 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 16 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 47), // void()(char *, char *, int, int *, int *, int *, int, int, int)
/* 19 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 21 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 25 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 26 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 27 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 28 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION, 47), // void()(char *, char *, int, int *, int *, int)
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 32 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 36 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 37 */ _CFFI_OP(_CFFI_OP_FUNCTION, 47), // void()(char *, char *, int, int *, int *, int, int)
/* 38 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 39 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 40 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 41 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 42 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 43 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 44 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 45 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 46 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 47 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_d_calculate_j(int x0, int * x1, int * x2, int * x3)
{
  return calculate_j(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_calculate_j(PyObject *self, PyObject *args)
{
  int x0;
  int * x1;
  int * x2;
  int * x3;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "calculate_j", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (int *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(2), arg1) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg2, (char **)&x2);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x2 = (int *)alloca((size_t)datasize);
    memset((void *)x2, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x2, _cffi_type(2), arg2) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg3, (char **)&x3);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x3 = (int *)alloca((size_t)datasize);
    memset((void *)x3, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x3, _cffi_type(2), arg3) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = calculate_j(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_calculate_j _cffi_d_calculate_j
#endif

static void _cffi_d_decompress_trans(char * x0, char * x1, int * x2, int * x3, int * x4, int * x5, int * x6, int x7, int x8, int x9)
{
  decompress_trans(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_decompress_trans(PyObject *self, PyObject *args)
{
  char * x0;
  char * x1;
  int * x2;
  int * x3;
  int * x4;
  int * x5;
  int * x6;
  int x7;
  int x8;
  int x9;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;

  if (!PyArg_UnpackTuple(args, "decompress_trans", 10, 10, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(7), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(7), arg1) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg2, (char **)&x2);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x2 = (int *)alloca((size_t)datasize);
    memset((void *)x2, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x2, _cffi_type(2), arg2) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg3, (char **)&x3);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x3 = (int *)alloca((size_t)datasize);
    memset((void *)x3, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x3, _cffi_type(2), arg3) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg4, (char **)&x4);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x4 = (int *)alloca((size_t)datasize);
    memset((void *)x4, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x4, _cffi_type(2), arg4) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (int *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(2), arg5) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg6, (char **)&x6);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x6 = (int *)alloca((size_t)datasize);
    memset((void *)x6, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x6, _cffi_type(2), arg6) < 0)
      return NULL;
  }

  x7 = _cffi_to_c_int(arg7, int);
  if (x7 == (int)-1 && PyErr_Occurred())
    return NULL;

  x8 = _cffi_to_c_int(arg8, int);
  if (x8 == (int)-1 && PyErr_Occurred())
    return NULL;

  x9 = _cffi_to_c_int(arg9, int);
  if (x9 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { decompress_trans(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_decompress_trans _cffi_d_decompress_trans
#endif

static void _cffi_d_padData(char * x0, char * x1, int x2, int * x3, int * x4, int x5)
{
  padData(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_padData(PyObject *self, PyObject *args)
{
  char * x0;
  char * x1;
  int x2;
  int * x3;
  int * x4;
  int x5;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "padData", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(7), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(7), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg3, (char **)&x3);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x3 = (int *)alloca((size_t)datasize);
    memset((void *)x3, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x3, _cffi_type(2), arg3) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg4, (char **)&x4);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x4 = (int *)alloca((size_t)datasize);
    memset((void *)x4, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x4, _cffi_type(2), arg4) < 0)
      return NULL;
  }

  x5 = _cffi_to_c_int(arg5, int);
  if (x5 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { padData(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_padData _cffi_d_padData
#endif

static void _cffi_d_tData(char * x0, char * x1, int x2, int * x3, int * x4, int * x5, int x6, int x7, int x8)
{
  tData(x0, x1, x2, x3, x4, x5, x6, x7, x8);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_tData(PyObject *self, PyObject *args)
{
  char * x0;
  char * x1;
  int x2;
  int * x3;
  int * x4;
  int * x5;
  int x6;
  int x7;
  int x8;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;

  if (!PyArg_UnpackTuple(args, "tData", 9, 9, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(7), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(7), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg3, (char **)&x3);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x3 = (int *)alloca((size_t)datasize);
    memset((void *)x3, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x3, _cffi_type(2), arg3) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg4, (char **)&x4);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x4 = (int *)alloca((size_t)datasize);
    memset((void *)x4, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x4, _cffi_type(2), arg4) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg5, (char **)&x5);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x5 = (int *)alloca((size_t)datasize);
    memset((void *)x5, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x5, _cffi_type(2), arg5) < 0)
      return NULL;
  }

  x6 = _cffi_to_c_int(arg6, int);
  if (x6 == (int)-1 && PyErr_Occurred())
    return NULL;

  x7 = _cffi_to_c_int(arg7, int);
  if (x7 == (int)-1 && PyErr_Occurred())
    return NULL;

  x8 = _cffi_to_c_int(arg8, int);
  if (x8 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { tData(x0, x1, x2, x3, x4, x5, x6, x7, x8); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_tData _cffi_d_tData
#endif

static void _cffi_d_tData_simple(char * x0, char * x1, int x2, int * x3, int * x4, int x5, int x6)
{
  tData_simple(x0, x1, x2, x3, x4, x5, x6);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_tData_simple(PyObject *self, PyObject *args)
{
  char * x0;
  char * x1;
  int x2;
  int * x3;
  int * x4;
  int x5;
  int x6;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;

  if (!PyArg_UnpackTuple(args, "tData_simple", 7, 7, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(7), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(7), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg3, (char **)&x3);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x3 = (int *)alloca((size_t)datasize);
    memset((void *)x3, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x3, _cffi_type(2), arg3) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg4, (char **)&x4);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x4 = (int *)alloca((size_t)datasize);
    memset((void *)x4, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x4, _cffi_type(2), arg4) < 0)
      return NULL;
  }

  x5 = _cffi_to_c_int(arg5, int);
  if (x5 == (int)-1 && PyErr_Occurred())
    return NULL;

  x6 = _cffi_to_c_int(arg6, int);
  if (x6 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { tData_simple(x0, x1, x2, x3, x4, x5, x6); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_tData_simple _cffi_d_tData_simple
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "calculate_j", (void *)_cffi_f_calculate_j, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_calculate_j },
  { "decompress_trans", (void *)_cffi_f_decompress_trans, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 6), (void *)_cffi_d_decompress_trans },
  { "padData", (void *)_cffi_f_padData, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 29), (void *)_cffi_d_padData },
  { "tData", (void *)_cffi_f_tData, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 18), (void *)_cffi_d_tData },
  { "tData_simple", (void *)_cffi_f_tData_simple, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 37), (void *)_cffi_d_tData_simple },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  5,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  48,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_tData(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_tData(void) { return NULL; }
#  else
     inittData(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_tData(void)
{
  return _cffi_init("tData", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
inittData(void)
{
  _cffi_init("tData", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
